# <font color='blue'>Data Science Academy - Programação Paralela em GPU</font>

## Multiplicação de Matrizes com NumPy

### Multiplicação Element-wise

Já vimos a multiplicação de matrizes com element-wise. Apenas para relembrar:

In [1]:
import numpy as np

In [2]:
# Definimos uma matriz
m = np.array([[1,2,3],[4,5,6]])
m

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
# Usamos o operador de multiplicação para multiplicar cada elemento da matriz por 0.50. 
# Isso vai gerar uma nova matriz n.
n = m * 0.50
n

array([[ 0.5,  1. ,  1.5],
       [ 2. ,  2.5,  3. ]])

In [4]:
# Multiplicamos as duas matrizes, element-wise
m * n

array([[  0.5,   2. ,   4.5],
       [  8. ,  12.5,  18. ]])

### Matrix Product

Para encontrar o produto da matriz, você usa a função matmul() do NumPy. O shape das matrizes precisa ser compatível.

In [5]:
a = np.array([[1,2,3,4],[5,6,7,8]])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [6]:
a.shape

(2, 4)

In [7]:
b = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
b

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [8]:
b.shape

(4, 3)

observe que o número de colunas da primeira matriz é igual ao número de linhas da segunda matriz. Relebrando as regras:

•	O número de colunas na matriz esquerda deve ser igual ao número de linhas na matriz direita.

•	A matriz de respostas sempre possui o mesmo número de linhas que a matriz esquerda e o mesmo número de colunas que a matriz direita.

•	Ordem importa aqui. Multiplicar A • B não é o mesmo que multiplicar B • A.

•	Os dados na matriz esquerda devem ser organizados como linhas, enquanto os dados na matriz direita devem ser organizados como colunas.


In [9]:
matriz_reposta = np.matmul(a, b)
matriz_reposta

array([[ 70,  80,  90],
       [158, 184, 210]])

In [10]:
matriz_reposta.shape

(2, 3)

In [11]:
# Se as matrizes tiverem shape incompatível, você recebe a mensagem de erro abaixo.
# Veja que A x B não é a mesma coisa que B x A na multiplicação de matrizes.
np.matmul(b, a)

ValueError: shapes (4,3) and (2,4) not aligned: 3 (dim 1) != 2 (dim 0)

### Função dot() do NumPy

Às vezes, você pode ver a função dot() do NumPy em lugares onde você esperaria um matmul. Acontece que os resultados das funções dot() e matmul() são os mesmos se as matrizes forem de duas dimensões.

In [12]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [13]:
np.dot(a,a)

array([[ 7, 10],
       [15, 22]])

In [14]:
# Podemos chamar a função dot() diretamente do objeto ndarray
a.dot(a) 

array([[ 7, 10],
       [15, 22]])

In [15]:
np.matmul(a,a)

array([[ 7, 10],
       [15, 22]])

Embora essas funções retornem os mesmos resultados para dados bidimensionais, você deve ter cuidado com o que você escolher ao trabalhar com outras formas de dados. Seguem abaixo referências nas documentações oficiais:

NumPy matmul() - https://docs.scipy.org/doc/numpy/reference/generated/numpy.matmul.html#numpy.matmul

NumPy dot() - https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html

## Fim