In [1]:
#Ativando o ambiente virtual
!conda activate tf_gpu

In [2]:
# Importando os pacotes
import numpy as np
import tensorflow as tf
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'

In [3]:
# Criando uma matriz identidade 2x3
identity_matrix = tf.eye(2, num_columns = 3)
print("\nMatriz Identidade 2x3")
print(identity_matrix)


Matriz Identidade 2x3
tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]], shape=(2, 3), dtype=float32)


In [4]:
# Criando uma matriz 2x3 randomicamente normalizada
A = tf.random.truncated_normal([2,3])
print("\nMatriz A - 2x3")
print(A)


Matriz A - 2x3
tf.Tensor(
[[-0.71074015 -0.51399463 -0.50820553]
 [ 0.70729107 -0.01629491 -0.15488191]], shape=(2, 3), dtype=float32)


In [5]:
# Criando uma matriz 2x3 com valores constantes
B = tf.fill([2,3], 5.0)
print("\nMatriz B - 2x3")
print(B)


Matriz B - 2x3
tf.Tensor(
[[5. 5. 5.]
 [5. 5. 5.]], shape=(2, 3), dtype=float32)


In [6]:
# Criando uma matriz 3x2 randomicamente uniforme
C = tf.random.uniform([3,2])
print("\nMatriz C - 3x2")
print(C)


Matriz C - 3x2
tf.Tensor(
[[0.8314984  0.2386694 ]
 [0.44032872 0.54580677]
 [0.04311943 0.2687844 ]], shape=(3, 2), dtype=float32)


In [7]:
# Convertendo um array numpy 3x3 para um tensor
array1 = np.array([[1., 2., 3.], [-3., -7., -1.], [0., 5., -2.]])
D = tf.convert_to_tensor(array1)
print("\nMatriz D")
print(D)


Matriz D
tf.Tensor(
[[ 1.  2.  3.]
 [-3. -7. -1.]
 [ 0.  5. -2.]], shape=(3, 3), dtype=float64)


In [8]:
# Adicione a matriz A com a matriz B
print("\nSoma A + B")
print(A+B)


Soma A + B
tf.Tensor(
[[4.28926   4.4860053 4.4917946]
 [5.707291  4.983705  4.845118 ]], shape=(2, 3), dtype=float32)


In [9]:
# Subtraia a matriz B da mesma matriz B
print("\nSubtrai B de B")
print(B-B)


Subtrai B de B
tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


In [10]:
# Multiplicação da Matriz A e C
print("\nMultiplicação de Matriz")
print(tf.matmul(A, C))


Multiplicação de Matriz
tf.Tensor(
[[-0.8392194  -0.58677137]
 [ 0.5742579   0.11828501]], shape=(2, 2), dtype=float32)


In [11]:
# Transposta da matriz C
print("\nTransposta Matriz C")
print(tf.transpose(C)) 


Transposta Matriz C
tf.Tensor(
[[0.8314984  0.44032872 0.04311943]
 [0.2386694  0.54580677 0.2687844 ]], shape=(2, 3), dtype=float32)


In [12]:
# Determinante da matriz D
print("\nDeterminante D")
print(tf.linalg.det(D))


Determinante D
tf.Tensor(-37.99999999999999, shape=(), dtype=float64)


In [13]:
# Matrix Inversa da matriz D
print("\nInversa da Matriz D")
print(tf.linalg.inv(D))


Inversa da Matriz D
tf.Tensor(
[[-0.5        -0.5        -0.5       ]
 [ 0.15789474  0.05263158  0.21052632]
 [ 0.39473684  0.13157895  0.02631579]], shape=(3, 3), dtype=float64)
