In [1]:
# Importando pacotes fundamentais
import keras
import tensorflow as tf
import pandas
import numpy as np
from keras.utils import np_utils
print (keras.__version__)
print (tf.__version__)

2.6.0
2.6.0


In [2]:
#Carregando dataset e incluindo header
dados = pandas.read_csv("wine.data.txt", names=["Class","Alcohol","Malic Alic","Ash","Alcanility of Ash","Magnesium",
                    "Total phenols","Flavanoids","Nonflavanoid phenols","Proanthocyanins","Color intensity","Hue","OD280_OD315_diluted wines",
                    "Proline"])

In [3]:
# Obtendo os valores de classe e armazenando em y
y = dados["Class"].values

In [4]:
print(y)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3]


In [5]:
# Ajustando o formato de y
# Converte array 1-D em matriz 
y_train = np_utils.to_categorical(y)

In [6]:
print(y_train)

[[0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1.

In [7]:
# Keras espera receber as classes em diferentes colunas. Como temos 3 classes, precisamos de 3 colunas.
y_train = y_train[:,1:4]

In [8]:
print(y_train)

[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0.

In [9]:
del(dados["Class"])
dados = dados.values

## Definindo a Arquitetura do Modelo

In [10]:
#Importe modelo sequencial
from keras.models import Sequential

#Importe das camadas rede neural
from keras.layers import Dense, Dropout, Activation, Flatten

#Importe otimizador
# from keras.optimizers import SGD

#Importe utilitários
from keras.utils import np_utils

## Construindo as Camadas

In [11]:
model = Sequential()

Camadas totalmente conectadas são definidas usando a classe Dense. Podemos especificar o número de neurônios na camada como o primeiro argumento, o método de inicialização como o segundo argumento com kernel_initializer e especificar a função de ativação usando o argumento activation.

O valor 'normal' no parâmetro kernel_initializer gera pequenos valores randômicos com uma distirbuição Graussiana (normal).

Usaremos a função de ativação ReLu nas duas primeiras camadas e a função sigmóide na camada de saída. Costumava-se usar as funções da ativação sigmoid e tanh para todas as camadas. Mas atualmente, o melhor desempenho é alcançado usando a função de ativação ReLu. Usamos um sigmoide nas camadas internas para garantir que nossa saída de rede esteja entre 0 e 1 e e função softmax na camada de saída, comumente usada em problemas de classificação.

In [12]:
model.add(Dense(40, input_dim = 13, kernel_initializer = 'normal', activation = 'relu'))

model.add(Dense(10, kernel_initializer = 'normal', activation = "sigmoid"))

model.add(Dropout(0.10))

model.add(Dense(5, kernel_initializer = 'normal', activation = "sigmoid"))

model.add(Dense(3, kernel_initializer = 'normal', activation = "softmax"))

## Otimização com Stochastic Gradient Descent

In [13]:
sgd = tf.keras.optimizers.Adam(learning_rate = 0.001, beta_1 = 0.9, beta_2 = 0.999, epsilon = 1e-08, decay = 0.0)

## Compilação do Modelo e Treinamento

In [14]:
model.compile(loss = 'categorical_crossentropy', optimizer = sgd,  metrics = ["acc"])

In [15]:
model.fit(dados, y_train, epochs = 1600, verbose = 1)

Epoch 1/1600
6/6 [==============================] - 1s 5ms/step - loss: 1.0966 - acc: 0.3989
Epoch 2/1600
6/6 [==============================] - 0s 4ms/step - loss: 1.0950 - acc: 0.3989
Epoch 3/1600
6/6 [==============================] - 0s 1ms/step - loss: 1.0936 - acc: 0.3989
Epoch 4/1600
6/6 [==============================] - 0s 3ms/step - loss: 1.0923 - acc: 0.3989
Epoch 5/1600
6/6 [==============================] - 0s 973us/step - loss: 1.0915 - acc: 0.3989
Epoch 6/1600
6/6 [==============================] - 0s 3ms/step - loss: 1.0899 - acc: 0.3989
Epoch 7/1600
6/6 [==============================] - 0s 995us/step - loss: 1.0894 - acc: 0.3989
Epoch 8/1600
6/6 [==============================] - 0s 3ms/step - loss: 1.0885 - acc: 0.3989
Epoch 9/1600
6/6 [==============================] - 0s 3ms/step - loss: 1.0879 - acc: 0.3989
Epoch 10/1600
6/6 [==============================] - 0s 945us/step - loss: 1.0873 - acc: 0.3989
Epoch 11/1600
6/6 [==============================] - 0s 3ms/ste

Epoch 88/1600
6/6 [==============================] - 0s 3ms/step - loss: 0.8054 - acc: 0.6742
Epoch 89/1600
6/6 [==============================] - 0s 1ms/step - loss: 0.7727 - acc: 0.6685
Epoch 90/1600
6/6 [==============================] - 0s 2ms/step - loss: 0.7736 - acc: 0.6742
Epoch 91/1600
6/6 [==============================] - 0s 1ms/step - loss: 0.7594 - acc: 0.6798
Epoch 92/1600
6/6 [==============================] - 0s 2ms/step - loss: 0.7645 - acc: 0.6742
Epoch 93/1600
6/6 [==============================] - 0s 909us/step - loss: 0.7464 - acc: 0.6798
Epoch 94/1600
6/6 [==============================] - 0s 3ms/step - loss: 0.7483 - acc: 0.6798
Epoch 95/1600
6/6 [==============================] - 0s 928us/step - loss: 0.7542 - acc: 0.6798
Epoch 96/1600
6/6 [==============================] - 0s 3ms/step - loss: 0.7450 - acc: 0.6798
Epoch 97/1600
6/6 [==============================] - 0s 1ms/step - loss: 0.7359 - acc: 0.6798
Epoch 98/1600
6/6 [==============================] - 0s 

6/6 [==============================] - 0s 818us/step - loss: 0.6054 - acc: 0.7022
Epoch 174/1600
6/6 [==============================] - 0s 3ms/step - loss: 0.5919 - acc: 0.7079
Epoch 175/1600
6/6 [==============================] - 0s 881us/step - loss: 0.5994 - acc: 0.7022
Epoch 176/1600
6/6 [==============================] - 0s 3ms/step - loss: 0.6037 - acc: 0.7022
Epoch 177/1600
6/6 [==============================] - 0s 874us/step - loss: 0.6070 - acc: 0.6966
Epoch 178/1600
6/6 [==============================] - 0s 3ms/step - loss: 0.5975 - acc: 0.7135
Epoch 179/1600
6/6 [==============================] - 0s 885us/step - loss: 0.5877 - acc: 0.7079
Epoch 180/1600
6/6 [==============================] - 0s 3ms/step - loss: 0.5835 - acc: 0.7022
Epoch 181/1600
6/6 [==============================] - 0s 2ms/step - loss: 0.5959 - acc: 0.7079
Epoch 182/1600
6/6 [==============================] - 0s 3ms/step - loss: 0.6095 - acc: 0.6910
Epoch 183/1600
6/6 [==============================] - 0s 

6/6 [==============================] - 0s 1ms/step - loss: 0.5608 - acc: 0.7079
Epoch 259/1600
6/6 [==============================] - 0s 3ms/step - loss: 0.5525 - acc: 0.7079
Epoch 260/1600
6/6 [==============================] - 0s 844us/step - loss: 0.5649 - acc: 0.7022
Epoch 261/1600
6/6 [==============================] - 0s 3ms/step - loss: 0.5570 - acc: 0.7079
Epoch 262/1600
6/6 [==============================] - 0s 895us/step - loss: 0.5569 - acc: 0.7079
Epoch 263/1600
6/6 [==============================] - 0s 3ms/step - loss: 0.5559 - acc: 0.7079
Epoch 264/1600
6/6 [==============================] - 0s 910us/step - loss: 0.5489 - acc: 0.7079
Epoch 265/1600
6/6 [==============================] - 0s 3ms/step - loss: 0.5718 - acc: 0.6910
Epoch 266/1600
6/6 [==============================] - 0s 788us/step - loss: 0.5891 - acc: 0.6910
Epoch 267/1600
6/6 [==============================] - 0s 3ms/step - loss: 0.5497 - acc: 0.7135
Epoch 268/1600
6/6 [==============================] - 0s 

6/6 [==============================] - 0s 3ms/step - loss: 0.5785 - acc: 0.6854
Epoch 344/1600
6/6 [==============================] - 0s 866us/step - loss: 0.5545 - acc: 0.7079
Epoch 345/1600
6/6 [==============================] - 0s 3ms/step - loss: 0.5420 - acc: 0.7135
Epoch 346/1600
6/6 [==============================] - 0s 857us/step - loss: 0.5650 - acc: 0.6966
Epoch 347/1600
6/6 [==============================] - 0s 3ms/step - loss: 0.5414 - acc: 0.7079
Epoch 348/1600
6/6 [==============================] - 0s 969us/step - loss: 0.5384 - acc: 0.7079
Epoch 349/1600
6/6 [==============================] - 0s 3ms/step - loss: 0.5397 - acc: 0.7079
Epoch 350/1600
6/6 [==============================] - 0s 1ms/step - loss: 0.5322 - acc: 0.7191
Epoch 351/1600
6/6 [==============================] - 0s 3ms/step - loss: 0.5317 - acc: 0.7191
Epoch 352/1600
6/6 [==============================] - 0s 954us/step - loss: 0.5311 - acc: 0.7135
Epoch 353/1600
6/6 [==============================] - 0s 

Epoch 429/1600
6/6 [==============================] - 0s 3ms/step - loss: 0.5318 - acc: 0.7191
Epoch 430/1600
6/6 [==============================] - 0s 797us/step - loss: 0.5281 - acc: 0.7135
Epoch 431/1600
6/6 [==============================] - 0s 2ms/step - loss: 0.5313 - acc: 0.7135
Epoch 432/1600
6/6 [==============================] - 0s 982us/step - loss: 0.5258 - acc: 0.7191
Epoch 433/1600
6/6 [==============================] - 0s 3ms/step - loss: 0.5388 - acc: 0.7079
Epoch 434/1600
6/6 [==============================] - 0s 1ms/step - loss: 0.5604 - acc: 0.7022
Epoch 435/1600
6/6 [==============================] - 0s 3ms/step - loss: 0.5207 - acc: 0.7191
Epoch 436/1600
6/6 [==============================] - 0s 767us/step - loss: 0.5270 - acc: 0.7135
Epoch 437/1600
6/6 [==============================] - 0s 3ms/step - loss: 0.5341 - acc: 0.7079
Epoch 438/1600
6/6 [==============================] - 0s 874us/step - loss: 0.5377 - acc: 0.7079
Epoch 439/1600
6/6 [======================

6/6 [==============================] - 0s 3ms/step - loss: 0.5145 - acc: 0.7191
Epoch 515/1600
6/6 [==============================] - 0s 3ms/step - loss: 0.5203 - acc: 0.7191
Epoch 516/1600
6/6 [==============================] - 0s 613us/step - loss: 0.5105 - acc: 0.7191
Epoch 517/1600
6/6 [==============================] - 0s 2ms/step - loss: 0.5114 - acc: 0.7191
Epoch 518/1600
6/6 [==============================] - 0s 900us/step - loss: 0.5226 - acc: 0.7191
Epoch 519/1600
6/6 [==============================] - 0s 3ms/step - loss: 0.5251 - acc: 0.7135
Epoch 520/1600
6/6 [==============================] - 0s 1ms/step - loss: 0.5150 - acc: 0.7191
Epoch 521/1600
6/6 [==============================] - 0s 3ms/step - loss: 0.5159 - acc: 0.7191
Epoch 522/1600
6/6 [==============================] - 0s 791us/step - loss: 0.5257 - acc: 0.7135
Epoch 523/1600
6/6 [==============================] - 0s 3ms/step - loss: 0.5342 - acc: 0.7135
Epoch 524/1600
6/6 [==============================] - 0s 73

6/6 [==============================] - 0s 932us/step - loss: 0.5439 - acc: 0.7022
Epoch 600/1600
6/6 [==============================] - 0s 3ms/step - loss: 0.5214 - acc: 0.7135
Epoch 601/1600
6/6 [==============================] - 0s 1ms/step - loss: 0.5093 - acc: 0.7191
Epoch 602/1600
6/6 [==============================] - 0s 3ms/step - loss: 0.5169 - acc: 0.7135
Epoch 603/1600
6/6 [==============================] - 0s 825us/step - loss: 0.5181 - acc: 0.7191
Epoch 604/1600
6/6 [==============================] - 0s 3ms/step - loss: 0.5086 - acc: 0.7135
Epoch 605/1600
6/6 [==============================] - 0s 885us/step - loss: 0.5161 - acc: 0.7135
Epoch 606/1600
6/6 [==============================] - 0s 3ms/step - loss: 0.5160 - acc: 0.7191
Epoch 607/1600
6/6 [==============================] - 0s 888us/step - loss: 0.5107 - acc: 0.7191
Epoch 608/1600
6/6 [==============================] - 0s 2ms/step - loss: 0.5192 - acc: 0.7191
Epoch 609/1600
6/6 [==============================] - 0s 

6/6 [==============================] - 0s 3ms/step - loss: 0.5114 - acc: 0.7191
Epoch 685/1600
6/6 [==============================] - 0s 770us/step - loss: 0.5091 - acc: 0.7191
Epoch 686/1600
6/6 [==============================] - 0s 3ms/step - loss: 0.5228 - acc: 0.7079
Epoch 687/1600
6/6 [==============================] - 0s 898us/step - loss: 0.5964 - acc: 0.6910
Epoch 688/1600
6/6 [==============================] - 0s 3ms/step - loss: 0.5933 - acc: 0.6854
Epoch 689/1600
6/6 [==============================] - 0s 815us/step - loss: 0.5087 - acc: 0.7191
Epoch 690/1600
6/6 [==============================] - 0s 3ms/step - loss: 0.5196 - acc: 0.7135
Epoch 691/1600
6/6 [==============================] - 0s 1ms/step - loss: 0.5163 - acc: 0.7135
Epoch 692/1600
6/6 [==============================] - 0s 3ms/step - loss: 0.5214 - acc: 0.7135
Epoch 693/1600
6/6 [==============================] - 0s 1ms/step - loss: 0.5209 - acc: 0.7135
Epoch 694/1600
6/6 [==============================] - 0s 3m

6/6 [==============================] - 0s 1ms/step - loss: 0.4717 - acc: 0.7191
Epoch 770/1600
6/6 [==============================] - 0s 3ms/step - loss: 0.4577 - acc: 0.7191
Epoch 771/1600
6/6 [==============================] - 0s 881us/step - loss: 0.4623 - acc: 0.7191
Epoch 772/1600
6/6 [==============================] - 0s 3ms/step - loss: 0.4741 - acc: 0.7191
Epoch 773/1600
6/6 [==============================] - 0s 912us/step - loss: 0.4654 - acc: 0.7191
Epoch 774/1600
6/6 [==============================] - 0s 3ms/step - loss: 0.4573 - acc: 0.7191
Epoch 775/1600
6/6 [==============================] - 0s 806us/step - loss: 0.4603 - acc: 0.7191
Epoch 776/1600
6/6 [==============================] - 0s 3ms/step - loss: 0.4737 - acc: 0.7135
Epoch 777/1600
6/6 [==============================] - 0s 1ms/step - loss: 0.4988 - acc: 0.7022
Epoch 778/1600
6/6 [==============================] - 0s 3ms/step - loss: 0.4747 - acc: 0.7079
Epoch 779/1600
6/6 [==============================] - 0s 88

6/6 [==============================] - 0s 970us/step - loss: 0.3532 - acc: 0.9382
Epoch 855/1600
6/6 [==============================] - 0s 3ms/step - loss: 0.3582 - acc: 0.9101
Epoch 856/1600
6/6 [==============================] - 0s 568us/step - loss: 0.3549 - acc: 0.9270
Epoch 857/1600
6/6 [==============================] - 0s 3ms/step - loss: 0.3422 - acc: 0.9438
Epoch 858/1600
6/6 [==============================] - 0s 1ms/step - loss: 0.3716 - acc: 0.9045
Epoch 859/1600
6/6 [==============================] - 0s 3ms/step - loss: 0.3546 - acc: 0.9270
Epoch 860/1600
6/6 [==============================] - 0s 994us/step - loss: 0.3369 - acc: 0.9101
Epoch 861/1600
6/6 [==============================] - 0s 3ms/step - loss: 0.3482 - acc: 0.9382
Epoch 862/1600
6/6 [==============================] - 0s 1ms/step - loss: 0.3584 - acc: 0.9326
Epoch 863/1600
6/6 [==============================] - 0s 3ms/step - loss: 0.3471 - acc: 0.9438
Epoch 864/1600
6/6 [==============================] - 0s 90

6/6 [==============================] - 0s 3ms/step - loss: 0.3213 - acc: 0.9157
Epoch 940/1600
6/6 [==============================] - 0s 836us/step - loss: 0.2699 - acc: 0.9494
Epoch 941/1600
6/6 [==============================] - 0s 3ms/step - loss: 0.2812 - acc: 0.9382
Epoch 942/1600
6/6 [==============================] - 0s 917us/step - loss: 0.2758 - acc: 0.9438
Epoch 943/1600
6/6 [==============================] - 0s 3ms/step - loss: 0.3018 - acc: 0.9213
Epoch 944/1600
6/6 [==============================] - 0s 887us/step - loss: 0.2656 - acc: 0.9438
Epoch 945/1600
6/6 [==============================] - 0s 3ms/step - loss: 0.2988 - acc: 0.9270
Epoch 946/1600
6/6 [==============================] - 0s 3ms/step - loss: 0.2767 - acc: 0.9270
Epoch 947/1600
6/6 [==============================] - 0s 1ms/step - loss: 0.2888 - acc: 0.9101
Epoch 948/1600
6/6 [==============================] - 0s 3ms/step - loss: 0.2626 - acc: 0.9438
Epoch 949/1600
6/6 [==============================] - 0s 70

6/6 [==============================] - 0s 1ms/step - loss: 0.2382 - acc: 0.9382
Epoch 1025/1600
6/6 [==============================] - 0s 3ms/step - loss: 0.2063 - acc: 0.9438
Epoch 1026/1600
6/6 [==============================] - 0s 1ms/step - loss: 0.2168 - acc: 0.9607
Epoch 1027/1600
6/6 [==============================] - 0s 3ms/step - loss: 0.1846 - acc: 0.9382
Epoch 1028/1600
6/6 [==============================] - 0s 865us/step - loss: 0.2185 - acc: 0.9157
Epoch 1029/1600
6/6 [==============================] - 0s 3ms/step - loss: 0.1952 - acc: 0.9438
Epoch 1030/1600
6/6 [==============================] - 0s 766us/step - loss: 0.2030 - acc: 0.9438
Epoch 1031/1600
6/6 [==============================] - 0s 3ms/step - loss: 0.1922 - acc: 0.9663
Epoch 1032/1600
6/6 [==============================] - 0s 1ms/step - loss: 0.1759 - acc: 0.9438
Epoch 1033/1600
6/6 [==============================] - 0s 3ms/step - loss: 0.1660 - acc: 0.9663
Epoch 1034/1600
6/6 [==============================]

6/6 [==============================] - 0s 937us/step - loss: 0.1459 - acc: 0.9663
Epoch 1109/1600
6/6 [==============================] - 0s 3ms/step - loss: 0.1278 - acc: 0.9775
Epoch 1110/1600
6/6 [==============================] - 0s 924us/step - loss: 0.1488 - acc: 0.9831
Epoch 1111/1600
6/6 [==============================] - 0s 3ms/step - loss: 0.1440 - acc: 0.9663
Epoch 1112/1600
6/6 [==============================] - 0s 706us/step - loss: 0.1407 - acc: 0.9663
Epoch 1113/1600
6/6 [==============================] - 0s 3ms/step - loss: 0.1353 - acc: 0.9831
Epoch 1114/1600
6/6 [==============================] - 0s 828us/step - loss: 0.1428 - acc: 0.9607
Epoch 1115/1600
6/6 [==============================] - 0s 3ms/step - loss: 0.1402 - acc: 0.9719
Epoch 1116/1600
6/6 [==============================] - 0s 1ms/step - loss: 0.1288 - acc: 0.9831
Epoch 1117/1600
6/6 [==============================] - 0s 3ms/step - loss: 0.1313 - acc: 0.9719
Epoch 1118/1600
6/6 [===========================

6/6 [==============================] - 0s 892us/step - loss: 0.1125 - acc: 0.9663
Epoch 1193/1600
6/6 [==============================] - 0s 3ms/step - loss: 0.1074 - acc: 0.9775
Epoch 1194/1600
6/6 [==============================] - 0s 878us/step - loss: 0.1045 - acc: 0.9831
Epoch 1195/1600
6/6 [==============================] - 0s 3ms/step - loss: 0.1057 - acc: 0.9831
Epoch 1196/1600
6/6 [==============================] - 0s 625us/step - loss: 0.1100 - acc: 0.9775
Epoch 1197/1600
6/6 [==============================] - 0s 3ms/step - loss: 0.0916 - acc: 0.9831
Epoch 1198/1600
6/6 [==============================] - 0s 3ms/step - loss: 0.1120 - acc: 0.9831
Epoch 1199/1600
6/6 [==============================] - 0s 808us/step - loss: 0.1135 - acc: 0.9663
Epoch 1200/1600
6/6 [==============================] - 0s 3ms/step - loss: 0.1056 - acc: 0.9831
Epoch 1201/1600
6/6 [==============================] - 0s 682us/step - loss: 0.1169 - acc: 0.9719
Epoch 1202/1600
6/6 [=========================

Epoch 1277/1600
6/6 [==============================] - 0s 3ms/step - loss: 0.0872 - acc: 0.9775
Epoch 1278/1600
6/6 [==============================] - 0s 834us/step - loss: 0.0973 - acc: 0.9831
Epoch 1279/1600
6/6 [==============================] - 0s 3ms/step - loss: 0.0891 - acc: 0.9775
Epoch 1280/1600
6/6 [==============================] - 0s 1ms/step - loss: 0.0983 - acc: 0.9663
Epoch 1281/1600
6/6 [==============================] - 0s 3ms/step - loss: 0.0772 - acc: 0.9888
Epoch 1282/1600
6/6 [==============================] - 0s 951us/step - loss: 0.0780 - acc: 0.9831
Epoch 1283/1600
6/6 [==============================] - 0s 3ms/step - loss: 0.0879 - acc: 0.9831
Epoch 1284/1600
6/6 [==============================] - 0s 941us/step - loss: 0.0818 - acc: 0.9831
Epoch 1285/1600
6/6 [==============================] - 0s 3ms/step - loss: 0.0787 - acc: 0.9831
Epoch 1286/1600
6/6 [==============================] - 0s 1ms/step - loss: 0.0802 - acc: 0.9831
Epoch 1287/1600
6/6 [=============

Epoch 1362/1600
6/6 [==============================] - 0s 3ms/step - loss: 0.0744 - acc: 0.9775
Epoch 1363/1600
6/6 [==============================] - 0s 1ms/step - loss: 0.0798 - acc: 0.9775
Epoch 1364/1600
6/6 [==============================] - 0s 3ms/step - loss: 0.0711 - acc: 0.9831
Epoch 1365/1600
6/6 [==============================] - 0s 860us/step - loss: 0.0718 - acc: 0.9831
Epoch 1366/1600
6/6 [==============================] - 0s 3ms/step - loss: 0.0657 - acc: 0.9888
Epoch 1367/1600
6/6 [==============================] - 0s 811us/step - loss: 0.0656 - acc: 0.9888
Epoch 1368/1600
6/6 [==============================] - 0s 3ms/step - loss: 0.0698 - acc: 0.9888
Epoch 1369/1600
6/6 [==============================] - 0s 780us/step - loss: 0.0640 - acc: 0.9888
Epoch 1370/1600
6/6 [==============================] - 0s 2ms/step - loss: 0.0623 - acc: 0.9888
Epoch 1371/1600
6/6 [==============================] - 0s 3ms/step - loss: 0.0629 - acc: 0.9888
Epoch 1372/1600
6/6 [=============

6/6 [==============================] - 0s 812us/step - loss: 0.0652 - acc: 0.9888
Epoch 1447/1600
6/6 [==============================] - 0s 3ms/step - loss: 0.0656 - acc: 0.9775
Epoch 1448/1600
6/6 [==============================] - 0s 1ms/step - loss: 0.0636 - acc: 0.9888
Epoch 1449/1600
6/6 [==============================] - 0s 3ms/step - loss: 0.0625 - acc: 0.9888
Epoch 1450/1600
6/6 [==============================] - 0s 3ms/step - loss: 0.0567 - acc: 0.9888
Epoch 1451/1600
6/6 [==============================] - 0s 2ms/step - loss: 0.0601 - acc: 0.9888
Epoch 1452/1600
6/6 [==============================] - 0s 3ms/step - loss: 0.0580 - acc: 0.9888
Epoch 1453/1600
6/6 [==============================] - 0s 970us/step - loss: 0.0584 - acc: 0.9888
Epoch 1454/1600
6/6 [==============================] - 0s 3ms/step - loss: 0.0619 - acc: 0.9888
Epoch 1455/1600
6/6 [==============================] - 0s 1ms/step - loss: 0.0568 - acc: 0.9888
Epoch 1456/1600
6/6 [==============================]

Epoch 1531/1600
6/6 [==============================] - 0s 3ms/step - loss: 0.0572 - acc: 0.9888
Epoch 1532/1600
6/6 [==============================] - 0s 896us/step - loss: 0.0563 - acc: 0.9888
Epoch 1533/1600
6/6 [==============================] - 0s 3ms/step - loss: 0.0532 - acc: 0.9888
Epoch 1534/1600
6/6 [==============================] - 0s 916us/step - loss: 0.0537 - acc: 0.9888
Epoch 1535/1600
6/6 [==============================] - 0s 3ms/step - loss: 0.0616 - acc: 0.9831
Epoch 1536/1600
6/6 [==============================] - 0s 1ms/step - loss: 0.0515 - acc: 0.9888
Epoch 1537/1600
6/6 [==============================] - 0s 3ms/step - loss: 0.0547 - acc: 0.9888
Epoch 1538/1600
6/6 [==============================] - 0s 950us/step - loss: 0.0492 - acc: 0.9888
Epoch 1539/1600
6/6 [==============================] - 0s 3ms/step - loss: 0.0552 - acc: 0.9888
Epoch 1540/1600
6/6 [==============================] - 0s 936us/step - loss: 0.0534 - acc: 0.9888
Epoch 1541/1600
6/6 [===========

In [16]:
score = model.evaluate(dados, y_train, verbose = 0)

In [17]:
print(score)

[0.04360950365662575, 0.9887640476226807]
