# <font color='blue'>Data Science Academy</font>
# <font color='blue'>Deep Learning I</font>

## Operações Element-wise com NumPy

### Primeiro, como você faria usando Python puro

Suponha que você tenha uma lista de números e que você deseja adicionar 5 a cada item da lista. Sem NumPy, você pode fazer algo como isto:

In [1]:
# Lista de valores
valores = [1, 2, 3, 4, 5]

In [2]:
# Looop for para adicionar 5 a cada elemento da lista
for i in range(len(valores)):
    valores[i] += 5

In [3]:
print(valores)

[6, 7, 8, 9, 10]


Isso faz sentido, mas é muito código para escrever e é mais lento, pois é Python puro.

### Agora sim, usando NumPy

In [4]:
import numpy as np

In [5]:
valores = [1,2,3,4,5]

In [6]:
valores = np.array(valores) + 5

In [7]:
print(valores)

[ 6  7  8  9 10]


Bem mais simples, não? Perceba que usamos a função array() para converter o objeto Python para um objeto NumPy e então realizar o cálculo.

Mas isso pode ficar ainda mais simples. NumPy oferece funções prontas para operações matemáticas como essa. Por exemplo:

In [8]:
valores = [1,2,3,4,5]

In [9]:
valores = np.add(valores, 5)

In [10]:
print(valores)

[ 6  7  8  9 10]


NumPy facilita muito nosso trabalho e vários frameworks de Deep Learning se baseiam no NumPy.

Um outro exemplo de operação element-wise com escalares e objetos ndarrays. Digamos que você tenha um objeto chamado "valores" e você queira reutilizá-lo, mas primeiro você precisa definir todos os seus valores em zero. Fácil, basta multiplicar por zero e atribuir o resultado de volta ao objeto, assim:

In [11]:
valores *= 0

In [12]:
print(valores)

[0 0 0 0 0]


### Operações Element-wise com Matrizes

As mesmas funções e operadores que trabalham com escalares e matrizes também funcionam com outras dimensões. Você só precisa se certificar de que os itens que você executa a operação possuem shapes compatíveis.

In [13]:
x = np.array([[1,3],[5,7]])
x

array([[1, 3],
       [5, 7]])

In [14]:
y = np.array([[2,4],[6,8]])
y

array([[2, 4],
       [6, 8]])

In [15]:
x + y

array([[ 3,  7],
       [11, 15]])

Isso funciona porque é uma multiplicação de elementos entre duas matrizes de forma (shape) idêntica. Experimente alterar o shape de uma das matrizes e repetir a soma. Você receberá uma mensagem de erro.

## Fim